name: Build and Deploy

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Verify environment configuration
      run: |
        echo "🔍 Environment Configuration Check"
        echo "REACT_APP_USE_SUPABASE: $REACT_APP_USE_SUPABASE"
        echo "REACT_APP_SUPABASE_URL: ${REACT_APP_SUPABASE_URL:0:30}..."
        echo "REACT_APP_SUPABASE_ANON_KEY: ${REACT_APP_SUPABASE_ANON_KEY:0:30}..."
        echo "REACT_APP_HOLIDAY_API_URL: $REACT_APP_HOLIDAY_API_URL"
        
        # 필수 환경변수 검증
        if [ "$REACT_APP_USE_SUPABASE" = "true" ]; then
          if [ -z "$REACT_APP_SUPABASE_URL" ] || [ -z "$REACT_APP_SUPABASE_ANON_KEY" ]; then
            echo "❌ Supabase configuration is incomplete!"
            exit 1
          fi
          echo "✅ Supabase configuration verified"
        else
          echo "⚠️ Using localStorage mode - not recommended for production"
        fi
      env:
        REACT_APP_USE_SUPABASE: true
        REACT_APP_SUPABASE_URL: https://qcsvkxtxtdljphyyrwcg.supabase.co
        REACT_APP_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjc3ZreHR4dGRsanBoeXlyd2NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjY1MjYsImV4cCI6MjA3Mjc0MjUyNn0.nvOp1fAJGgDBAXOw1tLIbDRRWZXHi7yf4zRsoUf95Gk
        REACT_APP_HOLIDAY_API_URL: https://holidays.hyunbin.page

    - name: Run tests
      run: npm test -- --coverage --watchAll=false --passWithNoTests

    - name: Build application
      run: CI=false npm run build
      env:
        REACT_APP_USE_SUPABASE: true
        REACT_APP_SUPABASE_URL: https://qcsvkxtxtdljphyyrwcg.supabase.co
        REACT_APP_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjc3ZreHR4dGRsanBoeXlyd2NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjY1MjYsImV4cCI6MjA3Mjc0MjUyNn0.nvOp1fAJGgDBAXOw1tLIbDRRWZXHi7yf4zRsoUf95Gk
        REACT_APP_HOLIDAY_API_URL: https://holidays.hyunbin.page

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
